import crypto from 'node:crypto';

// ─── Compact Peach merchantTransactionId generator ──────────────────
//
// Peach imposes a HARD 16-character limit on merchantTransactionId
// (per Visa / Mastercard 3DS2 mandate — violation returns
// `800.100.156` transaction declined format error).
//
// Our historic domain-side references (`hnpl_co_<20hex>`,
// `hnpl_<16hex>_a<n>`, `hnpl_settle_<uuid>`, `hnpl_reg_<uuid>`) all
// exceed that budget. Domain code keeps its own internal references
// unchanged; at the provider boundary we mint a compact 16-char ref
// and persist it alongside the internal one so the webhook echo can
// reconcile back.
//
// Scheme (exactly 16 characters, `[a-z0-9]`):
//
//   bn <purpose:1> <deterministic 13-char base36 hash of the seed>
//   └─┴───────────┴──────────────────────────────────────────────┘
//    2      1                        13
//
//   • `bn` — merchant prefix (BetterNow).
//   • purpose char:
//        c = Flow A checkout first-instalment CIT
//        i = Flow C MIT recurring instalment charge
//        s = self-settle-entire-plan MIT
//        r = Flow B card-registration-only (no payment row)
//   • body: first 8 bytes of sha256(seed) → BigInt → base36 → 13
//     chars (padded). 8 bytes = 64 bits ≈ 12.4 base36 digits, so 13
//     chars is enough headroom with zero-padding. Collision under a
//     BILLION distinct refs stays negligible.
//
// Determinism is a feature, not a bug: passing the same seed to
// mintPeachRef yields the same ref, so a mid-flight retry that
// re-enters the same code path echoes the same mtxid and Peach
// dedups. Callers that want a fresh ref per attempt (MIT retries)
// include the attempt number in the seed.

export type PeachRefPurpose = 'c' | 'i' | 's' | 'r';

const REF_PREFIX  = 'bn';
const REF_LENGTH  = 16;
const BODY_LENGTH = REF_LENGTH - REF_PREFIX.length - 1;  // 13

export function mintPeachRef(purpose: PeachRefPurpose, seed: string): string {
  if (!seed) throw new Error('mintPeachRef: seed is required');
  const hash = crypto.createHash('sha256').update(seed).digest();
  // Top 8 bytes → 64-bit unsigned int → base36
  const top8 = hash.subarray(0, 8);
  const bi   = BigInt('0x' + top8.toString('hex'));
  const body = bi.toString(36).padStart(BODY_LENGTH, '0').slice(-BODY_LENGTH);
  const ref  = `${REF_PREFIX}${purpose}${body}`;
  // Belt-and-braces: hard assert on the invariant so a regression in
  // this function can never quietly produce an over-length ref that
  // makes it to Peach.
  if (ref.length !== REF_LENGTH) {
    throw new Error(`mintPeachRef: produced ${ref.length}-char ref; scheme expects ${REF_LENGTH}`);
  }
  return ref;
}

/**
 * Recover the purpose char from a ref generated by mintPeachRef.
 * Returns null if the ref doesn't match our shape — used by the
 * webhook route to distinguish standalone card-registration events
 * (no payments row exists) from payment events.
 */
export function peachRefPurpose(ref: string | null | undefined): PeachRefPurpose | null {
  if (!ref) return null;
  if (ref.length !== REF_LENGTH) return null;
  if (!ref.startsWith(REF_PREFIX)) return null;
  const p = ref.charAt(REF_PREFIX.length);
  if (p === 'c' || p === 'i' || p === 's' || p === 'r') return p;
  return null;
}

// ─── Seed builders — one per call site ─────────────────────────────

/** Checkout / Flow A first-instalment CIT. Seed = instalment-1 payment id. */
export function checkoutRef(instalment1Id: string): string {
  return mintPeachRef('c', `co.${instalment1Id}`);
}

/**
 * Flow C MIT recurring charge. Seed encodes (payment, attempt) so
 * each attempt gets a fresh unique ref but retrying the SAME attempt
 * produces the SAME ref (Peach dedups on identical merchantTransactionId).
 */
export function instalmentAttemptRef(paymentId: string, attemptNumber: number): string {
  return mintPeachRef('i', `at.${paymentId}.${attemptNumber}`);
}

/** Self-settle-entire-plan MIT. Seed = settlement payment-row id. */
export function settleRef(settlementId: string): string {
  return mintPeachRef('s', `st.${settlementId}`);
}

/**
 * Flow B card-registration-only. No payment row exists to seed with,
 * and the same patient may add multiple cards, so each attempt gets a
 * fresh random seed. Caller supplies a UUID (or any unique-per-attempt
 * token).
 */
export function registrationRef(nonceUuid: string): string {
  return mintPeachRef('r', `rg.${nonceUuid}`);
}
