'use client';

import { useEffect, useId, useRef, useState } from 'react';

// ─── Peach Checkout V2 embedded widget mount ────────────────────────
//
// Renders the V2 embedded component in-page. Two use sites in the repo:
//
//   • Checkout bill-acceptance — the widget carries an amount + creates
//     a registration (INITIAL / INSTALLMENT / CIT). On onCompleted the
//     browser navigates to shopperResultUrl?checkoutId={id}; the server
//     route reads the checkoutId and asks Peach's V2 status API for
//     the final result.
//
//   • Card management "add card" — the widget runs in registration-only
//     mode. onCompleted navigates to /patient/payment-methods/complete
//     with the same checkoutId param.
//
// checkout.js loads the V2 embedded component. `PEACH_CHECKOUT_ENTITY_ID`
// is surfaced from the server via NEXT_PUBLIC_PEACH_CHECKOUT_ENTITY_ID
// — not a secret (the entity id is a public identifier used by the
// widget). The bearer token used to CREATE the checkout stays on the
// server; the browser only ever holds the short-lived checkoutId.
//
// ─── Mount-timing contract (why this looks careful) ────────────────
//
// The V2 checkout.js `.render(selector)` immediately calls
// document.querySelector against its DOM. If the render target isn't
// present at that instant, the widget throws "No element found" and
// the card form never appears (plan is left stuck at
// `pending_first_payment`; observed in prod 2026-07-30).
//
// Fix ordering — both preconditions before render():
//   (a) script-loaded: window.Checkout is set (either we injected
//       checkout.js this mount, or a prior mount left it cached).
//   (b) target-mounted: containerRef.current !== null AND has an id
//       resolved by useId(). Because useEffect runs post-commit, this
//       is guaranteed for THIS effect run — the ref never lags the DOM.
// render() is triggered from a React effect that depends on
// script-ready state. That takes the actual render call out of the raw
// browser `script.onload` handler (which fires outside React's commit
// discipline and could race a stale unmount) and onto React's schedule.
//
// The container div is rendered UNCONDITIONALLY in JSX from first
// paint. Its id is generated by useId() so multiple mounts on one
// page never collide on `#payment-form` and so we never depend on a
// shared global id.
//
// Single-init guard: initiatedForRef stores the checkoutId that has
// already been handed to Checkout.initiate on THIS instance. A
// re-render (or React 19 StrictMode's dev double-invoke) that re-fires
// the effect will short-circuit instead of calling render() twice on
// the same target — the second call would fail as Peach has already
// replaced the target's DOM.

type Props = {
  checkoutId:        string;
  entityId:          string;         // The Checkout V2 `key` — public.
  shopperResultUrl:  string;         // Where onCompleted navigates.
};

// Loose Checkout shape — checkout.js is loaded at runtime; we don't have
// its types. The V2 API is:
//   const checkout = Checkout.initiate({ key, checkoutId, events });
//   checkout.render('#target-id');
//
// Events fire on completion, cancellation, or expiry.
type CheckoutGlobal = {
  initiate: (opts: unknown) => { render: (target: string) => void };
};

function readCheckoutGlobal(): CheckoutGlobal | null {
  const w = window as unknown as { Checkout?: CheckoutGlobal };
  if (w.Checkout && typeof w.Checkout.initiate === 'function') return w.Checkout;
  return null;
}

export default function PeachWidget({ checkoutId, entityId, shopperResultUrl }: Props) {
  const containerRef      = useRef<HTMLDivElement | null>(null);
  const initiatedForRef   = useRef<string | null>(null);
  const [scriptReady, setScriptReady] = useState<boolean>(() => {
    // If Checkout was left on window by a prior mount (or by SSR bridging),
    // skip the script inject and treat the first render as script-ready.
    if (typeof window === 'undefined') return false;
    return readCheckoutGlobal() !== null;
  });
  const [error, setError] = useState<string | null>(null);

  // Sanitise useId() into a CSS-selector-safe id. useId returns tokens
  // like ":r0:" which are valid HTML ids but need escaping to be usable
  // in querySelector. Replacing colons keeps the id unique-per-instance
  // without escaping gymnastics at render-time.
  const rawId    = useId();
  const targetId = `peach-payment-form-${rawId.replace(/[^a-zA-Z0-9_-]/g, '')}`;

  // ── Effect 1: load checkout.js (idempotent) ──
  //
  // Runs on mount. If Checkout is already on window (cached from a
  // prior mount or another PeachWidget instance on the same page),
  // set scriptReady immediately. Otherwise inject the script tag and
  // flip scriptReady from its onload.
  //
  // Cleanup removes the script and drops the Checkout global so a
  // future mount gets fresh state — required because Peach's internal
  // module state doesn't cleanly re-render into a different DOM node.
  useEffect(() => {
    if (readCheckoutGlobal() !== null) {
      setScriptReady(true);
      return;
    }

    const src = process.env.NEXT_PUBLIC_PEACH_CHECKOUT_JS;
    if (!src) {
      console.error('[PeachWidget] NEXT_PUBLIC_PEACH_CHECKOUT_JS is not set');
      setError('The payment service is not configured. Please refresh the page or try again in a moment.');
      return;
    }

    let cancelled = false;
    const script = document.createElement('script');
    script.src         = src;
    script.async       = true;
    script.crossOrigin = 'anonymous';
    script.onload = (): void => {
      if (cancelled) return;
      if (readCheckoutGlobal() === null) {
        console.error('[PeachWidget] Checkout global missing after script load');
        setError('The payment form failed to initialise. Please refresh the page and try again.');
        return;
      }
      setScriptReady(true);
    };
    script.onerror = (): void => {
      if (cancelled) return;
      console.error('[PeachWidget] checkout.js failed to load');
      setError('Could not load the payment form. Please check your connection and refresh.');
    };
    document.body.appendChild(script);

    return () => {
      cancelled = true;
      script.remove();
      try {
        const w = window as unknown as { Checkout?: unknown };
        delete w.Checkout;
      } catch { /* ignore */ }
    };
    // Script src is invariant — depend on nothing, load once per mount.
  }, []);

  // ── Effect 2: initiate + render once BOTH preconditions hold ──
  //
  // Preconditions:
  //   • scriptReady === true
  //   • containerRef.current is a live DOM node with our unique id
  //   • initiatedForRef.current !== checkoutId (single-init per id)
  //
  // Runs from React's effect schedule, NOT from script.onload — that
  // guarantees the target element has been committed to the DOM by
  // the time render() fires.
  useEffect(() => {
    if (!scriptReady) return;
    const target = containerRef.current;
    if (!target) return;
    if (initiatedForRef.current === checkoutId) return;

    const checkoutGlobal = readCheckoutGlobal();
    if (!checkoutGlobal) {
      console.error('[PeachWidget] Checkout global missing at initiate time');
      setError('The payment form is not available. Please refresh the page.');
      return;
    }

    const navigateBack = (status: 'completed' | 'cancelled' | 'expired'): void => {
      const url = new URL(shopperResultUrl, window.location.origin);
      url.searchParams.set('checkoutId', checkoutId);
      if (status !== 'completed') url.searchParams.set('status', status);
      window.location.href = url.toString();
    };

    try {
      const checkout = checkoutGlobal.initiate({
        key:        entityId,
        checkoutId,
        // Card-only entry: number / expiry / CVV / cardholder — NO
        // billing-address form. `customisations.card.showBillingFields`
        // is an Embedded Checkout SDK render option that (per the SDK
        // reference) "overrides the backend configuration". It is a
        // WIDGET option, NOT a /v2/checkout POST field — so it cannot
        // trip the V2 "unknown field" body rejection that source/
        // frequency taught us about. The shopper's identity (email,
        // given name, surname) still travels on the server-side
        // customer block; only the address inputs are dropped.
        customisations: {
          card: { showBillingFields: false },
        },
        events: {
          onCompleted: () => navigateBack('completed'),
          onCancelled: () => navigateBack('cancelled'),
          onExpired:   () => navigateBack('expired'),
        },
      });
      checkout.render(`#${targetId}`);
      initiatedForRef.current = checkoutId;
    } catch (err) {
      console.error('[PeachWidget] Checkout.initiate threw', err);
      setError('Could not start the payment form. Please refresh the page and try again.');
    }
  }, [scriptReady, checkoutId, entityId, shopperResultUrl, targetId]);

  return (
    <div data-testid="peach-widget">
      {error && (
        <div
          role="alert"
          data-testid="peach-widget-error"
          className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800"
        >
          {error}
        </div>
      )}
      <div ref={containerRef} id={targetId} data-testid="peach-widget-target" />
    </div>
  );
}
