-- ─── Per-FK ON DELETE policy for FKs targeting profiles(id) ────────────────
--
-- WHY THIS MIGRATION EXISTS.
--
--   Migration 0044 added ON DELETE CASCADE on the SINGLE FK from
--   public.profiles → auth.users so deleting an auth user cleans up the
--   profile row. But profiles ITSELF is referenced by 11 other FKs across
--   the public schema. Those 11 had the default NO ACTION behaviour,
--   meaning a profile delete fails outright if any downstream row points
--   at it. With 0044 in place, that translates to: deleting an auth user
--   cascades to profiles, which then fails on the first downstream FK,
--   which rolls the whole cascade back. The end result is the same as
--   before 0044: you cannot delete a user with any history.
--
--   This migration assigns each of those 11 FKs an explicit ON DELETE
--   behaviour matching the POPIA-compliant posture for a credit product:
--
--     • Financial / audit records (plans, payments, payouts, refunds,
--       applications) MUST survive user deletion — the regulator (and
--       any future credit dispute) requires those rows. We RESTRICT
--       delete and require the operator to anonymise the profile
--       instead of hard-deleting.
--
--     • Structural rows that belong to the user and have no audit value
--       (practice memberships, saved payment methods, sent invitations)
--       CASCADE — they are personal data and disappear with the user.
--
--     • practices.owner_id is a special case: RESTRICT for now, because
--       a practice cannot be left ownerless. Before a practice owner can
--       ever be deleted, an owner-transfer flow must reassign ownership
--       to another practice_member. Flagged at the bottom of this file
--       as a follow-up.
--
-- DECISION TABLE (kept verbatim from the brief — change here and below
-- in lockstep if policy ever changes):
--
--   CASCADE (3):
--     practice_members.user_id
--     payment_methods.patient_id
--     patient_invitations.provider_id
--
--   RESTRICT (8):
--     plans.patient_id
--     plans.provider_id
--     payments.patient_id
--     payouts.provider_id
--     refunds.patient_id
--     applications.patient_id
--     practices.owner_id              (until owner-transfer flow exists)
--
--   Already CASCADE (no change needed, present for completeness):
--     plan_events.patient_id          (set in migration 0038)
--
-- NULLABILITY OF THE RESTRICT TARGETS (relevant only if we ever switch
-- one of them to SET NULL — currently we don't). All 7 RESTRICT-target
-- columns are NULLABLE today, so SET NULL would be syntactically valid
-- on every one of them:
--
--   plans.patient_id          NULLABLE (0021 DROP NOT NULL)
--   plans.provider_id         NULLABLE (added in 0021, never NOT NULL)
--   payments.patient_id       NULLABLE (0001 — never NOT NULL)
--   payouts.provider_id       NULLABLE (added in 0021, never NOT NULL)
--   refunds.patient_id        NULLABLE (0020 — never NOT NULL)
--   applications.patient_id   NULLABLE (0021 DROP NOT NULL)
--   practices.owner_id        NULLABLE (0001 — never NOT NULL)
--
-- We are choosing RESTRICT (block the delete) over SET NULL (orphan the
-- row) because RESTRICT forces the operator to explicitly anonymise
-- the profile before deletion. SET NULL would silently disconnect the
-- record from the (now-anonymous) user, which loses audit traceability.
--
-- IDEMPOTENCY.
--
--   A helper plpgsql function looks up each FK constraint by source
--   table + source column + referenced table, so the migration is
--   resilient to whatever constraint names Postgres autogenerated on
--   the live DB. The helper is dropped at the end of the migration.
--
--   The function is a no-op (with a NOTICE) if the named FK is missing
--   — which it won't be on a live HNPL DB, but makes the migration safe
--   to re-apply against a partial environment.

CREATE OR REPLACE FUNCTION public.__set_profile_fk_action(
  p_table   text,
  p_column  text,
  p_action  text                 -- 'CASCADE' | 'RESTRICT' | 'SET NULL' | 'NO ACTION'
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_fk_name text;
  v_attnum  int2;
BEGIN
  -- attnum of the source column.
  SELECT attnum INTO v_attnum
  FROM pg_attribute
  WHERE attrelid = format('public.%I', p_table)::regclass
    AND attname  = p_column
    AND NOT attisdropped;
  IF v_attnum IS NULL THEN
    RAISE NOTICE 'Column %.% not found — skipping', p_table, p_column;
    RETURN;
  END IF;

  -- The FK on (p_table, p_column) → public.profiles(id).
  SELECT con.conname INTO v_fk_name
  FROM pg_constraint con
  WHERE con.conrelid  = format('public.%I', p_table)::regclass
    AND con.confrelid = 'public.profiles'::regclass
    AND con.contype   = 'f'
    AND con.conkey    = ARRAY[v_attnum]::int2[]
  LIMIT 1;

  IF v_fk_name IS NULL THEN
    RAISE NOTICE 'No FK on %.% → profiles found — skipping', p_table, p_column;
    RETURN;
  END IF;

  -- Drop and recreate with the requested ON DELETE behaviour. Preserves
  -- the original constraint name so anyone reading pg_constraint
  -- continues to see the familiar identifier.
  EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I',
                 p_table, v_fk_name);
  EXECUTE format(
    'ALTER TABLE public.%I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES public.profiles(id) ON DELETE %s',
    p_table, v_fk_name, p_column, p_action
  );
  RAISE NOTICE 'Updated %.% (constraint %) → ON DELETE %',
    p_table, p_column, v_fk_name, p_action;
END $$;

-- ── Apply ───────────────────────────────────────────────────────────────────

-- CASCADE — structural user-owned rows, safe to remove with the user.
SELECT public.__set_profile_fk_action('practice_members',     'user_id',     'CASCADE');
SELECT public.__set_profile_fk_action('payment_methods',      'patient_id',  'CASCADE');
SELECT public.__set_profile_fk_action('patient_invitations',  'provider_id', 'CASCADE');

-- RESTRICT — financial / audit records that must survive user deletion.
SELECT public.__set_profile_fk_action('plans',         'patient_id',  'RESTRICT');
SELECT public.__set_profile_fk_action('plans',         'provider_id', 'RESTRICT');
SELECT public.__set_profile_fk_action('payments',      'patient_id',  'RESTRICT');
SELECT public.__set_profile_fk_action('payouts',       'provider_id', 'RESTRICT');
SELECT public.__set_profile_fk_action('refunds',       'patient_id',  'RESTRICT');
SELECT public.__set_profile_fk_action('applications',  'patient_id',  'RESTRICT');

-- RESTRICT until owner-transfer flow exists (see TODO at bottom).
SELECT public.__set_profile_fk_action('practices',     'owner_id',    'RESTRICT');

-- plan_events.patient_id already has ON DELETE CASCADE from migration 0038.
-- We re-assert it here for explicitness so future readers don't have to
-- cross-reference 0038.
SELECT public.__set_profile_fk_action('plan_events',   'patient_id',  'CASCADE');

-- ── Cleanup ─────────────────────────────────────────────────────────────────

DROP FUNCTION public.__set_profile_fk_action(text, text, text);

-- ═══════════════════════════════════════════════════════════════════════════
-- FOLLOW-UP REQUIRED before any practice-owner deletion path can ever fire:
--
--   1. Build an owner-transfer flow that lets an existing practice_member
--      with role='admin' be promoted to owner, with the old owner's
--      practices.owner_id reassigned in a single transaction.
--   2. The "delete this user" operator surface must check for any
--      practices.owner_id = user_id row and either refuse the delete OR
--      require the transfer to be done first.
--   3. Only then can we consider switching this FK to CASCADE / SET NULL.
-- ═══════════════════════════════════════════════════════════════════════════
